name: Bug
description: Something isn't right. Looks like a bug.
labels: "Type: Bug"
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a bug here, please make sure you are on the latest version of BentoBox or one that we're still supporting.

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: This may include a paste of the console error, a video, or detailed step by step instructions to help reconstruct the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: BentoBox version
      description: |
        Run `/bbox version` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/bbox version` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > bbox version
        Running PAPER 1.17.1.
        BentoBox version 1.17.2-SNAPSHOT-LOCAL
        Database JSON
        Loaded Game Worlds
        bskyblock_world (BSkyBlock): Overworld, Nether, The End
        Loaded Addons
        Border 3.2.0 (DISABLED)
        Boxed 1.2.0 (DISABLED)
        BSkyBlock 1.15.0 (ENABLED)
        Level 2.7.2-SNAPSHOT-LOCAL (ENABLED)
        Limits 1.17.1-SNAPSHOT-LOCAL (ENABLED)
        TwerkingForTrees 1.4.3-SNAPSHOT-LOCAL (ENABLED)
        Warps 1.10.2 (ENABLED)
        ```

        </details>
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Plugin list
      description: All plugins running on the server. Run `/plugins` on your server and **paste** the output here.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false

